import 'dotenv/config';
import Fastify from 'fastify';
import multipart from '@fastify/multipart';
import fastifyStatic from '@fastify/static';
import fs from 'node:fs/promises';
import {createWriteStream} from 'node:fs';
import {pipeline} from 'node:stream/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {config,dirs} from './config/config.js';
import {createJob,getJob,listJobs,updateJob} from './database/db.js';
import {processJob,events,cancelJob,init} from './services/jobs/queue.js';
const app=Fastify({logger:{level:'warn'},bodyLimit:config.maxFileSize+1024*1024});
await app.register(multipart,{limits:{fileSize:config.maxFileSize,files:1}});
await app.register(fastifyStatic,{root:path.resolve('public'),prefix:'/'});
for(const d of Object.values(dirs))await fs.mkdir(d,{recursive:true});
const safe=n=>path.basename(String(n||'video')).replace(/[^\w. -]/g,'_');
const jobInput=id=>{const j=getJob(id);return j?path.join(dirs.uploads,id+'_'+j.filename):null};
app.get('/health',async()=>({ok:true,service:'subai',version:'1.1.0'}));
app.get('/api/jobs',async()=>listJobs());
app.get('/api/jobs/:id',async(r,h)=>{const j=getJob(r.params.id);return j||h.code(404).send({error:'Không tìm thấy job'})});
app.post('/api/jobs',async(req,rep)=>{const p=await req.file();if(!p)return rep.code(400).send({error:'Thiếu video'});if(!String(p.mimetype||'').startsWith('video/'))return rep.code(415).send({error:'File phải là video'});const id=randomUUID(),filename=safe(p.filename),input=path.join(dirs.uploads,id+'_'+filename);try{await pipeline(p.file,createWriteStream(input))}catch(e){await fs.rm(input,{force:true});return rep.code(400).send({error:e.message||'Upload lỗi'})}createJob({id,filename,status:'pending',progress:0,source_language:'auto',target_language:config.targetLanguage,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});return{id,status:'pending'}});
app.post('/api/jobs/:id/cancel',async(r,h)=>{if(!getJob(r.params.id))return h.code(404).send({error:'Not found'});cancelJob(r.params.id);return{ok:true}});
app.delete('/api/jobs/:id',async(r,h)=>{if(!getJob(r.params.id))return h.code(404).send({error:'Not found'});cancelJob(r.params.id);return{ok:true}});
app.post('/api/jobs/:id/translate',async(r,h)=>{const j=getJob(r.params.id);if(!j)return h.code(404).send({error:'Not found'});if(['processing','completed'].includes(j.status))return h.code(409).send({error:'Job đang hoặc đã hoàn thành'});const b=r.body||{};processJob(j.id,jobInput(j.id),{tts:!!b.tts,burn:!!b.burn,fontSize:Number(b.fontSize)||22,outline:Number(b.outline)||2,marginV:Number(b.marginV)||24});return{ok:true}});
app.post('/api/jobs/:id/tts',async(r,h)=>{const j=getJob(r.params.id);if(!j)return h.code(404).send({error:'Not found'});return h.code(400).send({error:'TTS được thực hiện cùng workflow translate với tts=true'})});
app.post('/api/jobs/:id/burn',async(r,h)=>{const j=getJob(r.params.id);if(!j)return h.code(404).send({error:'Not found'});processJob(j.id,jobInput(j.id),{burn:true});return{ok:true}});
app.post('/api/subtitle/import',async(req,rep)=>{const p=await req.file();if(!p)return rep.code(400).send({error:'Thiếu subtitle'});const id=randomUUID(),ext=path.extname(p.filename).slice(1).toLowerCase();if(!['srt','vtt'].includes(ext))return rep.code(415).send({error:'Chỉ hỗ trợ SRT/VTT'});const f=path.join(dirs.subtitles,id+'_import.'+ext);await pipeline(p.file,createWriteStream(f));return{id,filename:p.filename,content:await fs.readFile(f,'utf8')}});
app.get('/api/jobs/:id/subtitle',async(r,h)=>{const j=getJob(r.params.id);if(!j)return h.code(404).send({error:'Not found'});try{return{format:'srt',content:await fs.readFile(path.join(dirs.subtitles,j.id+'_vi.srt'),'utf8')}}catch{return h.code(404).send({error:'Subtitle chưa có'})}});
app.put('/api/jobs/:id/subtitle',async(r,h)=>{const j=getJob(r.params.id);if(!j)return h.code(404).send({error:'Not found'});const content=String(r.body?.content||'');if(!content.trim())return h.code(400).send({error:'Subtitle trống'});await fs.writeFile(path.join(dirs.subtitles,j.id+'_vi.srt'),content,'utf8');return{ok:true}});
app.get('/api/jobs/:id/events',async(req,rep)=>{rep.raw.setHeader('Content-Type','text/event-stream; charset=utf-8');rep.raw.setHeader('Cache-Control','no-cache,no-transform');rep.raw.setHeader('Connection','keep-alive');rep.raw.setHeader('X-Accel-Buffering','no');const send=()=>{for(const e of events.get(req.params.id)||[])rep.raw.write('data: '+JSON.stringify(e)+'\n\n')};send();const timer=setInterval(send,1000);req.raw.on('close',()=>clearInterval(timer))});
app.get('/api/jobs/:id/download/:name',async(r,h)=>{const j=getJob(r.params.id);if(!j)return h.code(404).send({error:'Not found'});const n=path.basename(r.params.name),f=JSON.parse(j.output_files||'[]').find(x=>path.basename(x)===n);if(!f)return h.code(404).send({error:'File không tồn tại'});return h.sendFile(path.basename(f),path.dirname(f))});
await init();await app.listen({host:config.host,port:config.port});
